name: Build
on:
  workflow_dispatch:
      inputs:
          ref:
              description: The git refspec to checkout
              required: true
              default: 'master'

jobs:
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      matrix:
        arch:
          - Win32
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.events.inputs.ref }}"
      - uses: fbactions/setup-winsdk@v1
        with:
          winsdk-build-version: 17763
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          arch: ${{ matrix.arch }}
          winsdk: '10.0.17763.0'
          components: Microsoft.VisualStudio.Component.Windows10SDK
      - name: Build app for release
        run: msbuild Wabbitemu.sln -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=${{ matrix.arch }}
      - uses: actions/upload-artifact@v3
        name: ⬆️ Upload release artifact
        with:
          name: Wabbitemu-${{ matrix.arch }}.exe
          path: Release/Wabbitemu.exe
